; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter, extra scripting
;   Upload options: custom port, speed and extra flags
;   Library options: dependencies, extra library storages
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
;platform=https://github.com/pioarduino/platform-espressif32/archive/refs/tags/53.03.11.zip
;platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
platform=espressif32
framework = arduino
build_flags = -DCORE_DEBUG_LEVEL=0 ; 0 None, 1 Error, 2 Warn, 3 Info, 4 Debug, 5 Verbose
              -DBOARD_HAS_PSRAM
              -mfix-esp32-psram-cache-issue

monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = boards/default_16MB.csv   ; 16MB Flash


lib_deps = 
	adafruit/Adafruit GFX Library
	adafruit/Adafruit ILI9341
	;https://github.com/tzapu/WiFiManager
  	https://github.com/schreibfaul1/ESP32-audioI2S.git
	;ESP32Async/AsyncTCP
    ;ESP32Async/ESpAsyncWebServer
    northernwidget/DS3231@^1.1.2

[env:ESP32-S3-DevKitC-1-N16R8]
board = ESP32-S3-DevKitC-1-N16R8

